AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  util

  Sample SAM Template for util

Globals:
  Function:
    Timeout: 15
    MemorySize: 512

Resources:
  UtilFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: util/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          ES_ENDPOINT: 
          ES_INDEX: 
          ACCESS_KEY: 
          SECRET_KEY: 
      Policies:
        - DynamoDBCrudPolicy:
            TableName: 
              ImageTable
        - S3CrudPolicy:
            BucketName: 
              lolserverless
        - RekognitionDetectOnlyPolicy: {}


Outputs:
  UtilFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt UtilFunction.Arn
